#!/bin/zsh

# Configure keyboard layouts
setxkbmap -layout us,ara -variant ,digits grp:menu_toggle caps:escape &

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Initialize pipewire
pipewire &

# Compositor
picom &

# Notifications
dunst &

# Fix cursor [bspwm]
xsetroot -cursor_name left_ptr &

# Set the wallpaper
$HOME/bin/wallpaper.sh &

# Start the WM
dbus-run-session bspwm
