#!/bin/sh

# Configure keyboard layouts
setxkbmap -layout us,ara -variant ,digits grp:menu_toggle caps:escape &

# Hotkey daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Initialize pipewire
pipewire &

# Mirror screen
xrandr --output DP-2 --mode 1920x1080 --output eDP-1 --mode 1920x1080 --same-as DP-2 &

# Compositor
picom &

# Notifications
dunst &

# Fix cursor [bspwm]
xsetroot -cursor_name left_ptr &

# Set the wallpaper
$HOME/bin/wallpaper.sh &

# Start the WM
dbus-run-session bspwm
