#!/bin/sh
# Note: Should be excutable to run

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false
bspc config history_aware_focus  true

# Colors
bspc config normal_border_color "#1e1e2e"
bspc config active_border_color "#1e1e2e"
bspc config focused_border_color "#89b4fa"
bspc config presel-feedback_colour "#f5748c"

# Rules
bspc rule -a mpv state=floating
bspc rule -a "*:float:*" state=floating
