#!/bin/sh

# Environment variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export CARGO_HOME="$XDG_DATA_HOME/cargo"

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="Firefox"

# pfetch output
export PF_INFO="ascii title os host kernel uptime pkgs memory"

# Cargo env path
[ -f  $XDG_DATA_HOME/cargo/env ] && source $XDG_DATA_HOME/cargo/env
